### ISSUE TITLE
h5p api

### ISSUE THREAD

**Issue by MKdent** [sandstorm/NeosH5P#5]
First of all thank you for providing this really great Neos extension. Exactly what I was looking for. 
I got an error message when creating and editing the content regarding "form enctype". I had to add enctype="multipart/form-data" to edit.html and new.html.

Then a question about the h5p api. When I add the content element "
Course Presentation" you get the error message "Validating h5p package failed.
The system was unable to install the Interactive Video component from the package, it requires a newer version of the H5P plugin. This site is currently running version 1.14, whereas the required version is 1.15 or higher. You should consider upgrading and then try again."

Is there an easy way for you to upgrade the version? Course Presentation is one of the best h5p content elements, I think. Would be great to be able to use it.

**Comment by beheist** [comment]
Hi @MKdent,
sorry for not replying to this sooner, I didn't see the issue here. I am about to release a new version that will fix both issues. It upgrades H5P core to 1.20 so that the latest libraries will work. Also, it now has the upload functionality implemented, which means you can easily share H5P content between platforms :)
